# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'products', '0001_initial'), (b'products', '0002_auto_20171121_1852'), (b'products', '0003_auto_20171121_1906')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField(default='N|A')),
                ('price', models.DecimalField(decimal_places=2, default=9.99, max_digits=100)),
            ],
        ),
    ]
